disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - line_length
  - function_body_length
  - file_length
  - identifier_name
  - type_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
reporter: "xcode"
